import type {Metadata} from "next";
import "../styles/globals.scss";
import {Poppins} from "next/font/google";
import StoreProvider from "@/app/StoreProvider";


const poppins = Poppins({
  display: "swap",
  subsets: ["latin"],
  variable: "--poppins-font",
  weight: ["400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={poppins.className}>
      <StoreProvider>
        {children}
      </StoreProvider>
      </body>
      </html>
  );
}



